#!/bin/bash
set -e
export MINIMAX_API_HOST="https://api.minimaxi.com"
export MINIMAX_API_KEY="sk-cp-LYTvK2pbGQWpOheDDkI3nH9-GrC0XdAADVpPMSvRhmnyzAm3v4eaNzQnCK97WnwWtvYh_4ZmYYlxL6i2Lkht6UtMJCpbMsrKOZ7ODuRG_A9YVe9Uqf6L0M0"
SCRIPT="/root/.openclaw/skills/minimax-multimodal-toolkit/scripts/image/generate_image.sh"
OUT="/root/.openclaw/workspace/minimax-output/douyin09_today"
mkdir -p "$OUT"

prompt_001="A lone figure walking on a long winding mountain road at dawn, misty atmosphere, cinematic lighting, warm golden sunrise breaking through clouds, shoes worn from the journey, determined stride, photorealistic, low saturation tones, Chinese landscape style"
prompt_002="A person building a stone wall with bare hands in a quiet countryside, sweat on brow, sunset backlighting, dust particles in the air, rugged determination, documentary photography style, muted earthy tones"
prompt_003="Close-up of eyes carefully observing a calligraphy brush stroke, a master calligrapher's hand in frame, afternoon light through rice paper screen, contemplative atmosphere, shallow depth of field, warm ink tones"
prompt_004="A person sitting alone in a traditional library, afternoon sunlight streaming through lattice windows, dust motes floating in light beams, rows of ancient books, serene and contemplative mood, cinematic composition"
prompt_005="Hands gently picking up fallen autumn leaves from a stone garden path, soft morning light, raked gravel patterns visible, zen garden atmosphere, meditative quality, close-up perspective, warm earth tones"
prompt_006="A worn notebook on a wooden desk, pen resting across the open page, notes and ideas written carefully, warm desk lamp glow, late night study atmosphere, intimate and quiet mood"
prompt_007="Two people in a traditional tea house having a warm conversation, steam rising from teacups, soft winter light through paper windows, respectful listening postures, friendship and humility depicted, cinematic emotional tone"
prompt_008="A mentor and student sitting by a tranquil pond, autumn maple leaves falling, the mentor gesturing thoughtfully while the student listens attentively, Chinese scholar garden setting, warm golden light"
prompt_009="A single candle burning in a dark room, its warm glow illuminating an open book, the flame representing sincerity and dedication, quiet midnight atmosphere, poetic and contemplative mood, soft warm light"
prompt_010="A person standing on a hilltop at sunrise with arms slightly raised, vast landscape stretching below, golden morning mist, moment of epiphany, spiritual and inspiring atmosphere, cinematic wide shot"
prompt_011="Five stone steps ascending a mountain path, each step illuminated by different quality of light representing the five types of diligence, morning mist, Chinese ink painting aesthetic merged with photorealism"
prompt_012="A traditional Chinese scholar's desk at dawn, withered brush, scattered manuscripts, a small potted pine tree, the desk lamp casting long shadows, scene of dedicated work, low warm light"
prompt_013="Long exposure photograph of a hiking trail at twilight, a single headlamp glowing in the distance, winding mountain path, stars beginning to appear, sense of solitary determination, cinematic atmosphere"
prompt_014="A farmer's weathered hands holding rich soil, dawn light illuminating the earth, seeds scattered across the palm, symbolic of fruitful labor, close-up documentary style, warm earth tones"
prompt_015="An elderly craftsman using a magnifying glass to examine fine wood grain, hands steady and experienced, workshop filled with natural northern light, focus and precision, shallow depth of field"
prompt_016="A person gazing out of a rain-streaked window at a blurred city at night, reflections in glass, contemplative mood, urban solitude, cinematic bokeh lights in background, cool blue tones"
prompt_017="A neat desk surface with organized sticky notes, a pen, a small succulent plant, morning sunlight from window, every small object in its proper place, minimal and focused workspace aesthetic"
prompt_018="Hands tying a knot on a worn leather journal, the journal filled with handwritten entries, warm afternoon light on the cover, ritual of recording thoughts, intimate close-up perspective"
prompt_019="A young person bowing respectfully to an elderly master in a traditional courtyard, cherry blossom petals falling, atmosphere of mutual respect and learning, soft spring light, emotional and dignified composition"
prompt_020="Group discussion around a circular table in a modern library, diverse people sharing ideas respectfully, warm pendant lighting above, collaborative learning atmosphere, humanistic documentary style"
prompt_021="A person meditating in a mountain monastery at sunrise, clouds floating below, bell with golden light rim, spiritual devotion, zen Buddhist atmosphere, ethereal and peaceful, wide cinematic framing"
prompt_022="Close-up of an open ancient book with beautiful calligraphy, fingers gently turning the page, dramatic side lighting casting shadows across the text, reverence for knowledge, warm golden tones"
prompt_023="A worn but sturdy wooden boat oar resting against a misty riverbank at dawn, representing persistent effort through rough waters, soft grey-blue morning tones, poetic and symbolic composition"
prompt_024="A calligraphy scroll unfurling in slow motion in a sunlit traditional hall, the characters 勤奋 rendered in powerful xingshū style, warm afternoon light illuminating the ink, elegant atmosphere"
prompt_025="A marathon runner at the precise moment of crossing the finish line alone, empty racetrack, triumphant pose, dramatic sky, exhaustion and accomplishment in the expression, cinematic sports photography"
prompt_026="Time-lapse style photograph of a bamboo grove, each stalk at different growth stages, morning dew, representing steady daily progress, serene and metaphorical, lush green tones"
prompt_027="A detective's eye viewed through a magnifying glass revealing hidden details in an old photograph, mystery and discovery, dramatic chiaroscuro lighting, cinematic noir atmosphere"
prompt_028="A child staring intently at a butterfly landing on their finger, pure wonder and focus in the expression, soft garden bokeh background, golden hour warmth, innocent observation"
prompt_029="Stack of worn practice calligraphy sheets covering a desk, each showing gradual improvement in brush strokes, late afternoon studio light, the daily discipline of mastery visible in the accumulated papers"
prompt_030="A well-worn leather toolbox on a workbench, each tool marked by years of use, afternoon light creating dramatic shadows across the well-organized workspace, honoring craftsmanship"
prompt_031="A teacher writing an encouraging note on a student's homework, red pen in hand, warm desk lamp glow, the gesture of guidance, intimate educational moment, documentary warmth"
prompt_032="Group of diverse people clapping genuinely for someone giving a speech, warm atmosphere of genuine appreciation, soft focus background, human connection and support, emotional documentary style"
prompt_033="A paper lantern floating in a night sky among stars, its warm glow representing sincere heart, long exposure photograph, magical realism aesthetic, dreamy and aspirational atmosphere"
prompt_034="A person lighting incense in a mountain temple, smoke curling upward toward ancient stone carvings, spiritual devotion, early morning light, profound tranquility, cinematic composition"
prompt_035="A split image: left side shows a chaotic messy desk, right side shows a perfectly organized one, transition through the middle, symbolic of discipline and diligent habits, clean editorial style"
prompt_036="A vast library with a single reader at a distant desk, warm lamplight creating a pool of light in the darkness, the figure small against towering bookshelves, knowledge as a lighthouse"
prompt_037="A tiny figure climbing an enormous spiral staircase that reaches into the clouds, perspective distortion making the stairs monumental, surreal metaphorical image of the long journey of diligence"
prompt_038="The same mountain path photographed in four seasons: spring blossoms, summer green, autumn leaves, winter snow, showing the consistent walker returning through all conditions, triptych composition"
prompt_039="Two hands shaking in a business setting, but the camera focuses on the eyes of both people meeting for the first time, reading character through careful observation, dramatic close-up"
prompt_040="An artist studying their own reflection in a mirror while painting, double exposure effect blending self-portrait and painting, introspection and self-awareness, moody studio lighting"
prompt_041="Hands sweeping fallen leaves from a stone path in a zen garden, the meditative quality of small consistent actions, early morning mist, the beauty of humble daily rituals, peaceful atmosphere"
prompt_042="A small water droplet falling into a still pond creating perfect ripples, macro photography, representing how small diligent actions create lasting impact, meditative quality"
prompt_043="A proud-looking young person listening with genuine surprise to an elderly person's story, the expression shift from skepticism to genuine respect, warm human connection, cinematic street photography"
prompt_044="A microphone on a podium with a small sign saying 倾听 in Chinese characters, empty conference hall, spotlight creating atmosphere of the importance of listening, minimalist composition"
prompt_045="Water eroding through stone over centuries, the drop finally breaking through creating a small hole, representing how sincere persistent effort conquers even the hardest obstacles, macro nature photography"
prompt_046="A heart made of origami paper floating in a sunbeam, the delicate art of patience and heartfelt dedication, white background with soft light, minimalist and symbolic composition"
prompt_047="Five rivers converging into one powerful waterfall at sunset, each tributary representing one type of diligence, the unified flow representing successful outcomes, majestic nature photography"
prompt_048="A compass on a wooden navigation table, the needle pointing steadily north, representing finding the right direction through diligent practice, warm nautical atmosphere, golden afternoon light"
prompt_049="A lighthouse at the edge of a cliff in a storm, its beam cutting through rain and darkness, guiding ships to safety, representing finding direction through diligent effort, dramatic cinematic photography"
prompt_050="The final scene: a person standing at a mountain summit watching the sunrise, arms relaxed at sides, the long journey completed, golden light washing over the vast landscape below, sense of peace and arrival, cinematic wide shot"

for i in $(seq -f "%03g" 1 50); do
  prompt_var="prompt_$i"
  prompt="${!prompt_var}"
  echo "Generating img_$i.jpg..."
  bash "$SCRIPT" --prompt "$prompt" --aspect-ratio 9:16 -o "$OUT/img_$i.jpg"
  echo "img_$i done"
done

echo "ALL 50 IMAGES COMPLETE"
